### ISSUE TITLE
Rollback transaction in Solidus 2.10

### ISSUE THREAD

**Issue by Henrik41** [jtapia/solidus_favorites#4]
Hi There. I tested your gem in Solidus 2.10 but it is not working as unable to save the transactions. Probably a validation issue.

**Comment by jtapia** [comment]
Thank you to let us know about the issue, we just updated the extension to support `v2.9.0` and `v2.10.0`, if update the gem running `bundle update solidus_favorites`, you'll ready to use it

**Comment by Henrik41** [comment]
Amazing! Thank you for your help.
